if [[ -z "$XDG_CONFIG_HOME" ]]
then
    export XDG_CONFIG_HOME="$HOME/.config/"
fi

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source ~/.config/zsh/powerlevel10k/powerlevel10k.zsh-theme
source ~/.config/bash/z/z.sh
source ~/.config/zsh/datadog.zsh

# Use Control-D instead of Escape to switch to NORMAL mode
VIM_MODE_VICMD_KEY='^D'
source ~/.config/zsh/zsh-vim-mode/zsh-vim-mode.plugin.zsh

HISTFILE=~/.zsh_history
HISTSIZE=100000000
SAVEHIST=100000000
setopt INC_APPEND_HISTORY
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_DUPS

alias ..="cd .."
alias ...="cd ../.."
alias ll="ls -alh --color=auto --group-directories-first"
alias grep="grep --color=auto --line-buffered"

export NVM_DIR="$XDG_CONFIG_HOME/nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
fi

export SSH_ENV="/Users/richard.nguyen/.ssh/environment"
start_ssh_agent() {
    echo "Initialising new SSH agent..."
    ssh-agent -s | sed 's/^echo/#echo/' > ${SSH_ENV}
    echo succeeded
    chmod 600 ${SSH_ENV}
    . ${SSH_ENV} > /dev/null
    ssh-add -k;
}

# Source SSH settings, if applicable
load_ssh_session() {
    if [ -f "${SSH_ENV}" ]; then
        . ${SSH_ENV} > /dev/null
        #ps ${SSH_AGENT_PID} doesn't work under cywgin
        ps aux ${SSH_AGENT_PID} | grep 'ssh-agent -s$' > /dev/null || {
            start_ssh_agent;
        }
    else
        start_ssh_agent;
    fi
}

load_ssh_session

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
